version: '3.8'

services:
  searxng:
    image: searxng/searxng:latest
    ports:
      - "8095:8080"
    volumes:
      - ./searxng_data:/etc/searxng:rw

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8090:8000"
    volumes:
      - ./chromadb_data:/chroma_data

  postgres:
    image: postgres:16
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./server:/app/server
    depends_on:
      - postgres
      - chromadb

  web-ui:
    build:
      context: ./clients/web
      dockerfile: Dockerfile
    ports:
      - "3040:3040"
    volumes:
      - ./clients/web:/app/clients/web
    depends_on:
      - server

volumes:
  postgres_data:
  chromadb_data:
  searxng_data: 