name: Chore / task
description: Engineering work that is not a bug or feature (refactor, infra, docs, tooling).
title: "Task: "
body:
  - type: markdown
    attributes:
      value: |
        Use this for refactors, maintenance, infra, docs, and other engineering tasks.

  - type: textarea
    id: outcome
    attributes:
      label: Desired outcome
      description: What should be true when this task is complete?
      placeholder: "We can ..., the system ..., docs updated ..., etc."
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope / affected areas
      description: What parts of the monorepo are impacted?
      placeholder: "@curiositi/platform, @curiositi/worker, packages/share, CI, etc."

  - type: textarea
    id: plan
    attributes:
      label: Proposed approach
      description: High-level plan or notes for implementation.
      placeholder: |
        - ...
        - ...

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Checklist of what must be done.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Risks / rollout
      description: Any risks, migrations, backwards compatibility, or rollout steps.

  - type: checkboxes
    id: done
    attributes:
      label: Definition of done
      options:
        - label: "`bun run check` passes"
        - label: "`bun run build` passes (if relevant)"
        - label: Docs updated (if relevant)
        - label: No secrets/credentials committed
